import { ThemeMode } from '../store/useAppStore';

export const themeTokens: Record<ThemeMode, Record<string, string>> = {
  light: { bg:'#f0f2f5', sidebar:'#fff', sidebarAlt:'#f6f8fb', border:'#d9e1ea', text:'#0f172a', muted:'#6b7280', accent:'#3390ec', accentSoft:'#e7f1fd', surface:'#fff', chatBg:'#dbe6ef', incoming:'#fff', outgoing:'#dff5c8', panel:'rgba(255,255,255,0.96)', shadow:'0 20px 40px rgba(15,23,42,0.12)' },
  dark:  { bg:'#08111b', sidebar:'#101926', sidebarAlt:'#162233', border:'#243246', text:'#e5edf7', muted:'#94a3b8', accent:'#60a5fa', accentSoft:'#172a40', surface:'#101926', chatBg:'#0b1420', incoming:'#132132', outgoing:'#153221', panel:'rgba(16,25,38,0.98)', shadow:'0 24px 48px rgba(0,0,0,0.35)' }
};

export const createStyles = (p: typeof themeTokens.light) => ({
  authWrap: { minHeight:'100vh', display:'grid', placeItems:'center', background:`linear-gradient(180deg, ${p.chatBg} 0%, ${p.bg} 100%)` },
  authCard: { width:420, maxWidth:'calc(100vw - 32px)', background:p.surface, padding:28, borderRadius:20, boxShadow:p.shadow, display:'grid', gap:14 },
  authLogo: { width:56, height:56, borderRadius:16, background:p.accent, color:'#fff', display:'grid', placeItems:'center', fontSize:28, fontWeight:700 },
  switcher: { display:'flex', gap:8 },
  switchBtn: { flex:1, padding:'10px 12px', borderRadius:12, border:`1px solid ${p.border}`, background:p.surface, color:p.text, cursor:'pointer' },
  switchActive: { flex:1, padding:'10px 12px', borderRadius:12, border:'none', background:p.accentSoft, color:p.accent, cursor:'pointer', fontWeight:700 },
  input: { width:'100%', padding:'12px 14px', borderRadius:12, border:`1px solid ${p.border}`, outline:'none', background:p.surface, color:p.text, boxSizing:'border-box' },
  primaryBtn: { padding:'12px 16px', borderRadius:12, border:'none', background:p.accent, color:'#fff', cursor:'pointer', fontWeight:700 },
  secondaryBtn: { padding:'10px 14px', borderRadius:12, border:`1px solid ${p.border}`, background:p.surface, color:p.text, cursor:'pointer', fontWeight:600 },
  dangerBtn: { padding:'10px 14px', borderRadius:12, border:'none', background:'#dc2626', color:'#fff', cursor:'pointer', fontWeight:700 },
  errorBox: { background:'#fff1f2', color:'#be123c', border:'1px solid #fecdd3', borderRadius:12, padding:10, fontSize:14 },
  successBox: { background:'#ecfdf5', color:'#047857', border:'1px solid #a7f3d0', borderRadius:12, padding:10, fontSize:14 },
  layout: { display:'grid', gridTemplateColumns:'430px 1fr', minHeight:'100vh', fontFamily:'Inter,Arial,sans-serif', background:p.bg, position:'relative' },
  toast: { position:'fixed', top:16, right:16, zIndex:30, background:'#111827', color:'#fff', padding:'10px 14px', borderRadius:12, boxShadow:'0 10px 30px rgba(0,0,0,0.2)' },
  sidebar: { background:p.sidebar, borderRight:`1px solid ${p.border}`, display:'grid', gridTemplateRows:'auto auto auto auto auto 1fr', overflow:'hidden' },
  sidebarTopbar: { display:'grid', gridTemplateColumns:'48px 1fr auto', gap:10, alignItems:'center', padding:14, borderBottom:`1px solid ${p.border}` },
  iconBtn: { width:44, height:44, borderRadius:12, border:`1px solid ${p.border}`, background:p.surface, color:p.text, cursor:'pointer', fontSize:18 },
  searchInput: { width:'100%', padding:'12px 14px', borderRadius:12, border:`1px solid ${p.border}`, background:p.sidebarAlt, color:p.text },
  selectInput: { padding:'12px 10px', borderRadius:12, border:`1px solid ${p.border}`, background:p.sidebarAlt, color:p.text },
  meCard: { display:'flex', gap:12, alignItems:'center', padding:14, borderBottom:`1px solid ${p.border}` },
  meAvatar: { width:48, height:48, borderRadius:999, background:p.accent, color:'#fff', display:'grid', placeItems:'center', fontWeight:700 },
  meName: { fontWeight:700, color:p.text },
  meMeta: { fontSize:13, color:p.muted },
  logoutBtn: { padding:'10px 12px', borderRadius:12, border:'none', background:p.sidebarAlt, color:p.text, cursor:'pointer', fontWeight:600 },
  settingsCard: { margin:'0 14px 14px', padding:14, borderRadius:16, background:p.sidebarAlt, border:`1px solid ${p.border}`, display:'grid', gap:12 },
  settingsTitle: { fontWeight:700, color:p.text },
  settingsHint: { color:p.muted, fontSize:13 },
  settingsSection: { display:'grid', gap:8 },
  settingsSectionDanger: { display:'grid', gap:8, paddingTop:8, borderTop:`1px dashed ${p.border}` },
  settingsLabel: { fontWeight:600, color:p.text, fontSize:14 },
  settingsLabelDanger: { fontWeight:700, color:'#dc2626', fontSize:14 },
  segmentedRow: { display:'flex', gap:8 },
  segmentedBtn: { flex:1, padding:'10px 12px', borderRadius:12, border:`1px solid ${p.border}`, background:p.surface, color:p.text, cursor:'pointer' },
  segmentedActive: { flex:1, padding:'10px 12px', borderRadius:12, border:'none', background:p.accentSoft, color:p.accent, cursor:'pointer', fontWeight:700 },
  newChatBar: { padding:'0 14px 14px' },
  newChatBtn: { width:'100%', padding:'12px 16px', borderRadius:14, border:'none', background:p.accent, color:'#fff', cursor:'pointer', fontWeight:700 },
  tabsWrap: { display:'flex', gap:8, padding:'0 14px 12px' },
  tabBtn: { flex:1, padding:'10px 12px', borderRadius:12, border:`1px solid ${p.border}`, background:p.surface, color:p.text, cursor:'pointer' },
  tabActive: { flex:1, padding:'10px 12px', borderRadius:12, border:'none', background:p.accentSoft, color:p.accent, cursor:'pointer', fontWeight:700 },
  panelWrap: { overflow:'auto', padding:'0 10px 12px' },
  panelTitle: { fontSize:15, fontWeight:700, color:p.text, padding:'4px 8px 8px' },
  panelHint: { fontSize:13, color:p.muted, padding:'0 8px 10px' },
  userList: { display:'grid', gap:4 },
  userRow: { display:'flex', alignItems:'center', gap:12, width:'100%', border:'none', background:p.surface, padding:10, borderRadius:14, cursor:'pointer' },
  avatarSmall: { width:42, height:42, borderRadius:999, background:p.accentSoft, color:p.accent, display:'grid', placeItems:'center', fontWeight:700, flexShrink:0 },
  userName: { fontWeight:600, color:p.text },
  userMeta: { fontSize:12, color:p.muted },
  messageCta: { color:p.accent, fontWeight:700, fontSize:13 },
  emptyState: { padding:10, color:p.muted, fontSize:14 },
  groupBox: { marginTop:14, padding:10, borderRadius:16, background:p.sidebarAlt, display:'grid', gap:10 },
  groupMembers: { display:'grid', gap:6, maxHeight:140, overflow:'auto' },
  memberLabel: { fontSize:14, color:p.text },
  chatList: { display:'grid', gap:6 },
  chatRowWrap: { display:'grid', gridTemplateColumns:'1fr auto', alignItems:'center', borderRadius:14 },
  chatRow: { display:'flex', alignItems:'center', gap:12, width:'100%', border:'none', padding:10, borderRadius:14, cursor:'pointer', background:'transparent', color:p.text },
  pinBtn: { marginRight:8, padding:'8px 10px', borderRadius:10, border:'none', background:p.sidebarAlt, color:p.text, cursor:'pointer', fontSize:12 },
  chatTopLine: { display:'flex', justifyContent:'space-between', alignItems:'center', gap:8 },
  chatName: { fontWeight:700, color:p.text, whiteSpace:'nowrap', overflow:'hidden', textOverflow:'ellipsis' },
  chatTime: { fontSize:12, color:p.muted },
  chatSubline: { fontSize:13, color:p.muted, whiteSpace:'nowrap', overflow:'hidden', textOverflow:'ellipsis' },
  unreadBadge: { minWidth:22, height:22, borderRadius:999, background:p.accent, color:'#fff', display:'grid', placeItems:'center', fontSize:12, padding:'0 6px', marginRight:8 },
  main: { display:'grid', gridTemplateRows:'72px 1fr auto', background:p.chatBg },
  chatHeader: { display:'flex', alignItems:'center', gap:12, padding:'0 18px', background:p.surface, borderBottom:`1px solid ${p.border}` },
  avatar: { width:44, height:44, borderRadius:999, background:p.accent, color:'#fff', display:'grid', placeItems:'center', fontWeight:700 },
  chatHeaderTitle: { fontWeight:700, color:p.text },
  chatHeaderMeta: { fontSize:13, color:p.muted },
  messagesArea: { padding:20, overflow:'auto', display:'grid', gap:10, alignContent:'start', backgroundImage: themeTokens.light.bg === p.bg ? 'radial-gradient(rgba(255,255,255,0.3) 1px, transparent 1px)' : 'radial-gradient(rgba(255,255,255,0.06) 1px, transparent 1px)', backgroundSize:'24px 24px' },
  emptyCanvas: { margin:'auto', background:p.panel, padding:'16px 20px', borderRadius:16, color:p.muted },
  bubble: { maxWidth:560, borderRadius:18, padding:'10px 12px', boxShadow: themeTokens.light.bg === p.bg ? '0 6px 18px rgba(15,23,42,0.08)' : '0 10px 24px rgba(0,0,0,0.25)' },
  bubbleAuthor: { fontSize:12, fontWeight:700, color:p.accent, marginBottom:4 },
  bubbleText: { color:p.text, lineHeight:1.45, whiteSpace:'pre-wrap' },
  bubbleMeta: { marginTop:6, fontSize:11, color:p.muted, textAlign:'right' },
  attachmentsList: { marginTop:8, display:'grid', gap:6 },
  attachmentLink: { color:p.accent, textDecoration:'none', fontSize:14 },
  replyPreview: { padding:'8px 10px', borderRadius:12, background:p.accentSoft, marginBottom:8, fontSize:13, color:p.text },
  reactionsRow: { display:'flex', gap:6, flexWrap:'wrap', marginTop:8 },
  reactionChip: { background:p.sidebarAlt, borderRadius:999, padding:'4px 8px', fontSize:12, color:p.text },
  messageActions: { display:'flex', gap:6, flexWrap:'wrap', marginTop:8 },
  actionBtn: { padding:'4px 8px', borderRadius:8, border:'none', background:p.sidebarAlt, color:p.text, cursor:'pointer', fontSize:12 },
  composerWrap: { background:p.surface, borderTop:`1px solid ${p.border}` },
  contextBar: { display:'flex', justifyContent:'space-between', alignItems:'center', padding:'10px 14px', background:p.accentSoft, borderBottom:`1px solid ${p.border}` },
  contextBarEdit: { display:'flex', justifyContent:'space-between', alignItems:'center', padding:'10px 14px', background:p.sidebarAlt, borderBottom:`1px solid ${p.border}` },
  contextClose: { width:28, height:28, borderRadius:999, border:'none', background:p.surface, color:p.text, cursor:'pointer' },
  composerHint: { padding:'8px 14px 0', color:p.muted, fontSize:12 },
  composer: { display:'grid', gridTemplateColumns:'1fr auto auto', gap:10, alignItems:'end', padding:14, background:p.surface },
  composerTextarea: { width:'100%', padding:'14px 16px', borderRadius:18, border:`1px solid ${p.border}`, outline:'none', background:p.sidebarAlt, color:p.text, resize:'none', minHeight:52, maxHeight:180, boxSizing:'border-box', fontFamily:'inherit', lineHeight:1.45 },
  fileBadge: { margin:'10px 14px 0', background:p.sidebarAlt, color:p.text, borderRadius:12, padding:'8px 12px', fontSize:13 },
  attachBtn: { width:44, height:44, borderRadius:14, background:p.sidebarAlt, display:'grid', placeItems:'center', cursor:'pointer', color:p.text },
  sendBtn: { padding:'12px 18px', borderRadius:14, border:'none', background:p.accent, color:'#fff', cursor:'pointer', fontWeight:700 },
  sideDrawer: { position:'absolute', right:20, top:88, width:320, maxHeight:420, overflow:'auto', background:p.panel, border:`1px solid ${p.border}`, borderRadius:16, boxShadow:p.shadow, padding:14, zIndex:5, color:p.text },
  drawerTitle: { fontWeight:700, color:p.text, marginBottom:10 },
  drawerItem: { padding:'8px 0', borderBottom:`1px solid ${p.border}`, fontSize:14, color:p.text }
});